language: node_js
node_js:
- '0.11'
- '0.10'
after_success: npm run coveralls && npm run test-browser
env:
  global:
  - secure: LARVYxq4Xr2k0JJ9MZvWxN/nlbifKKv6WqaMOe4vAIXX3UB7ubFDphjeJv3H6LYySpGD9GcqTTAY5nh3TdpPVaI4I/fRK0LRIS9imLgESfwMpqSXENYFNExa3x5bWb7uSkBWnuCltXpXw2lPkWImYC2tGgzi+zTc+OAiH6RAHRs=
  - secure: GoQybtE6tjxGmGC0bZMOyz0B5ifg5zNP0psjw8oP7l9MCZXE5veYIv8Su0sQaiq+c/3pdvuPCtOfqTiOIF6U/z7fG0XACKxXu47ogX/qZ1tTUJQjqvmhWLHUDdQCkIjuQ/Wtk1YssxpbO0pquD5kC0d1gZ6PCNcxi2uHAaqAs28=
